package com.lumira.backend.quiz;

import com.lumira.backend.card.Card;
import com.lumira.backend.common.domain.ArtifactOwner;
import com.lumira.backend.common.error.ResourceNotFoundException;
import com.lumira.backend.common.error.ValidationException;
import com.lumira.backend.resource.ArtifactType;
import com.lumira.backend.resource.ResourceAuthorizationService;
import com.lumira.backend.resource.ResourceShare;
import com.lumira.backend.resource.ResourceShareRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service
public class QuizService {
    private final QuizRepository quizzes;
    private final QuizQuestionRepository questions;
    private final QuizQuestionOptionRepository options;
    private final QuizAttemptRepository attempts;
    private final QuizAttemptAnswerRepository answers;
    private final QuizAttemptAnswerOptionRepository answerOptions;
    private final ResourceShareRepository shares;
    private final ResourceAuthorizationService authorization;
    private final QuizResponseMapper mapper;

    public QuizService(QuizRepository quizzes, QuizQuestionRepository questions,
            QuizQuestionOptionRepository options, QuizAttemptRepository attempts,
            QuizAttemptAnswerRepository answers, QuizAttemptAnswerOptionRepository answerOptions,
            ResourceShareRepository shares, ResourceAuthorizationService authorization,
            QuizResponseMapper mapper) {
        this.quizzes = quizzes;
        this.questions = questions;
        this.options = options;
        this.attempts = attempts;
        this.answers = answers;
        this.answerOptions = answerOptions;
        this.shares = shares;
        this.authorization = authorization;
        this.mapper = mapper;
    }

    @Transactional
    public QuizResponse create(UUID cardId, UUID actorId, QuizCreateRequest request) {
        authorization.requirePrivateArtifactCardForCreate(cardId, actorId);
        validateText(request.title(), "title", true);
        validateText(request.description(), "description", false);
        validateQuestions(request.questions());
        if (request.questions().stream().anyMatch(q -> q.id() != null || q.options().stream().anyMatch(o -> o.id() != null))) {
            throw new ValidationException("Question and option IDs are generated by the server on create");
        }
        Quiz quiz = quizzes.saveAndFlush(new Quiz(ArtifactOwner.forCard(cardId), request.title(), request.description()));
        persistQuestions(quiz.getId(), request.questions());
        return mapper.from(quiz, authorization.isOwner(quiz.getOwner(), actorId));
    }

    @Transactional(readOnly = true)
    public List<QuizResponse> list(UUID cardId, UUID actorId) {
        Card card = authorization.requireCardReadable(cardId, actorId);
        List<Quiz> values;
        if (!card.isShared()) {
            values = quizzes.findByOwner_OwningCardIdOrderByCreatedAtDesc(cardId);
        } else {
            List<UUID> ids = shares.findByCardIdAndActiveTrueOrderByCreatedAtAsc(cardId).stream()
                    .filter(s -> s.getQuizId() != null).map(ResourceShare::getQuizId).toList();
            var visible = new LinkedHashMap<UUID, Quiz>();
            if (card.isOwnedBy(actorId)) {
                quizzes.findByOwner_OwningCardIdOrderByCreatedAtDesc(cardId).forEach(quiz -> visible.put(quiz.getId(), quiz));
            }
            quizzes.findAllById(ids).forEach(quiz -> visible.put(quiz.getId(), quiz));
            values = visible.values().stream().sorted(java.util.Comparator.comparing(Quiz::getCreatedAt).reversed()).toList();
        }
        Set<UUID> ownedCardIds = authorization.ownedCardIds(actorId, values.stream()
                .map(Quiz::getOwner).filter(owner -> !owner.isUserOwned())
                .map(ArtifactOwner::getOwningCardId).toList());
        return mapper.fromMany(values, q -> q.getOwner().isUserOwned()
                ? q.getOwner().getOwningUserId().equals(actorId)
                : ownedCardIds.contains(q.getOwner().getOwningCardId()), Set.copyOf(
                card.isShared() ? shares.findByCardIdAndActiveTrueOrderByCreatedAtAsc(cardId).stream()
                        .filter(s -> s.getQuizId() != null).map(ResourceShare::getQuizId).toList() : List.of()));
    }

    @Transactional(readOnly = true)
    public QuizResponse get(UUID quizId, UUID actorId) {
        Quiz quiz = load(quizId);
        authorization.requireArtifactReadable(quiz.getOwner(), ArtifactType.QUIZ, quizId, "Quiz not found", actorId);
        return mapper.from(quiz, authorization.isOwner(quiz.getOwner(), actorId));
    }

    @Transactional
    public QuizResponse update(UUID quizId, UUID actorId, QuizPatchRequest request) {
        Quiz quiz = quizzes.findByIdForUpdate(quizId).orElseThrow(this::notFound);
        authorization.requireArtifactOwner(quiz.getOwner(), "Quiz not found", actorId);
        if (request.title() != null) validateText(request.title(), "title", true);
        if (request.description() != null) validateText(request.description(), "description", false);
        Map<UUID, QuizQuestion> oldQuestions = questions.findByQuizIdOrderByPositionAsc(quizId).stream()
                .collect(Collectors.toMap(QuizQuestion::getId, Function.identity()));
        Map<UUID, List<QuizQuestionOption>> oldOptions = options.findByQuestionIdInOrderByQuestionIdAscPositionAsc(oldQuestions.keySet())
                .stream().collect(Collectors.groupingBy(QuizQuestionOption::getQuestionId));
        if (request.questions() != null) {
            validateQuestions(request.questions());
            validateRetainedIds(request.questions(), oldQuestions, oldOptions);
        }
        quiz.update(request.title(), request.description());
        quizzes.saveAndFlush(quiz);
        if (request.questions() != null) {
            replaceQuestions(quizId, request.questions(), oldQuestions, oldOptions);
        }
        return mapper.from(quiz, true);
    }

    @Transactional
    public void delete(UUID quizId, UUID actorId) {
        Quiz quiz = quizzes.findByIdForUpdate(quizId).orElseThrow(this::notFound);
        authorization.requireArtifactOwner(quiz.getOwner(), "Quiz not found", actorId);
        quizzes.delete(quiz);
    }

    @Transactional
    public QuizAttemptResponse submit(UUID quizId, UUID actorId, QuizAttemptRequest request) {
        Quiz quiz = quizzes.findByIdForUpdate(quizId).orElseThrow(this::notFound);
        authorization.requireArtifactReadable(quiz.getOwner(), ArtifactType.QUIZ, quizId, "Quiz not found", actorId);
        List<QuizQuestion> currentQuestions = questions.findByQuizIdOrderByPositionAsc(quizId);
        List<UUID> questionIds = currentQuestions.stream().map(QuizQuestion::getId).toList();
        Map<UUID, List<QuizQuestionOption>> currentOptions = options.findByQuestionIdInOrderByQuestionIdAscPositionAsc(questionIds)
                .stream().collect(Collectors.groupingBy(QuizQuestionOption::getQuestionId));
        if (request.answers().size() != currentQuestions.size()) {
            throw new ValidationException("Submit exactly one answer for every Quiz question");
        }
        Map<UUID, UUID> selectedByQuestion = new HashMap<>();
        Set<UUID> seenOptionIds = new HashSet<>();
        for (QuizAttemptRequest.AnswerInput answer : request.answers()) {
            if (answer.questionId() == null || answer.optionId() == null ||
                    selectedByQuestion.putIfAbsent(answer.questionId(), answer.optionId()) != null ||
                    !seenOptionIds.add(answer.optionId())) {
                throw new ValidationException("Quiz answers contain a duplicate or missing identifier");
            }
        }
        if (!selectedByQuestion.keySet().equals(new HashSet<>(questionIds))) {
            throw new ValidationException("Quiz answers contain unknown or missing questions");
        }
        List<ResolvedAnswer> resolvedAnswers = new ArrayList<>();
        int correctCount = 0;
        for (QuizQuestion question : currentQuestions) {
            List<QuizQuestionOption> questionOptions = currentOptions.getOrDefault(question.getId(), List.of());
            UUID selectedOptionId = selectedByQuestion.get(question.getId());
            QuizQuestionOption selected = questionOptions.stream().filter(o -> o.getId().equals(selectedOptionId)).findFirst()
                    .orElseThrow(() -> new ValidationException("Selected option does not belong to its question"));
            QuizQuestionOption correct = questionOptions.stream().filter(QuizQuestionOption::isCorrect).findFirst()
                    .orElseThrow(() -> new ValidationException("Quiz question has no valid correct answer"));
            boolean isCorrect = selected.isCorrect();
            if (isCorrect) correctCount++;
            resolvedAnswers.add(new ResolvedAnswer(question, questionOptions, selected, correct, isCorrect));
        }
        Instant submittedAt = Instant.now();
        QuizAttempt attempt = attempts.saveAndFlush(new QuizAttempt(quizId, actorId,
                correctCount, currentQuestions.size(), submittedAt));
        List<QuizAttemptAnswerOption> persistedOptions = new ArrayList<>();
        for (ResolvedAnswer resolved : resolvedAnswers) {
            QuizQuestion question = resolved.question();
            QuizQuestionOption selected = resolved.selected();
            QuizQuestionOption correct = resolved.correct();
            boolean isCorrect = resolved.isCorrect();
            QuizAttemptAnswer savedAnswer = answers.saveAndFlush(new QuizAttemptAnswer(attempt.getId(),
                    question.getId(), question.getPosition(), question.getPrompt(), selected.getId(),
                    selected.getText(), correct.getId(), correct.getText(), isCorrect));
            for (QuizQuestionOption option : resolved.options()) {
                persistedOptions.add(new QuizAttemptAnswerOption(savedAnswer.getId(), option.getId(),
                        option.getPosition(), option.getText(), option.getId().equals(selected.getId()), option.isCorrect()));
            }
        }
        answerOptions.saveAll(persistedOptions);
        answerOptions.flush();
        return response(attempt, answers.findByAttemptIdOrderByQuestionPositionAsc(attempt.getId()), persistedOptions);
    }

    @Transactional(readOnly = true)
    public List<QuizAttemptResponse> myAttempts(UUID quizId, UUID actorId) {
        Quiz quiz = load(quizId);
        authorization.requireArtifactReadable(quiz.getOwner(), ArtifactType.QUIZ, quizId, "Quiz not found", actorId);
        List<QuizAttempt> own = attempts.findByQuizIdAndUserIdOrderBySubmittedAtDesc(quizId, actorId);
        return own.stream().map(attempt -> response(attempt,
                answers.findByAttemptIdOrderByQuestionPositionAsc(attempt.getId()), null)).toList();
    }

    private QuizAttemptResponse response(QuizAttempt attempt, List<QuizAttemptAnswer> attemptAnswers,
            List<QuizAttemptAnswerOption> optionSnapshot) {
        Map<UUID, List<QuizAttemptAnswerOption>> optionsByAnswer;
        if (optionSnapshot == null) {
            optionsByAnswer = answerOptions.findByAnswerIdInOrderByAnswerIdAscPositionAsc(
                            attemptAnswers.stream().map(QuizAttemptAnswer::getId).toList())
                    .stream().collect(Collectors.groupingBy(QuizAttemptAnswerOption::getAnswerId));
        } else {
            optionsByAnswer = optionSnapshot.stream().collect(Collectors.groupingBy(QuizAttemptAnswerOption::getAnswerId));
        }
        List<QuizAttemptResponse.AnswerSnapshot> snapshots = attemptAnswers.stream().map(answer -> {
            List<QuizAttemptResponse.OptionSnapshot> optionResponses = optionsByAnswer.getOrDefault(answer.getId(), List.of())
                    .stream().sorted(java.util.Comparator.comparingInt(QuizAttemptAnswerOption::getPosition))
                    .map(option -> new QuizAttemptResponse.OptionSnapshot(option.getOptionId(), option.getPosition(),
                            option.getText(), option.isSelected(), option.isCorrect())).toList();
            return new QuizAttemptResponse.AnswerSnapshot(answer.getQuestionId(), answer.getPromptSnapshot(),
                    answer.getSelectedOptionId(), answer.getSelectedOptionText(), answer.getCorrectOptionId(),
                    answer.getCorrectOptionText(), answer.isCorrect(), optionResponses);
        }).toList();
        return new QuizAttemptResponse(attempt.getId(), attempt.getQuizId(), attempt.getUserId(),
                attempt.getCorrectCount(), attempt.getTotalQuestions(), attempt.getCreatedAt(),
                attempt.getSubmittedAt(), snapshots);
    }

    private void persistQuestions(UUID quizId, List<QuizQuestionInput> inputs) {
        for (QuizQuestionInput input : inputs) {
            QuizQuestion question = questions.saveAndFlush(new QuizQuestion(quizId, input.position(), input.prompt().strip()));
            for (QuizOptionInput option : input.options()) {
                options.save(new QuizQuestionOption(question.getId(), option.position(),
                        option.text().strip(), option.correct()));
            }
        }
        options.flush();
    }

    private void replaceQuestions(UUID quizId, List<QuizQuestionInput> inputs,
            Map<UUID, QuizQuestion> oldQuestions, Map<UUID, List<QuizQuestionOption>> oldOptions) {
        Set<UUID> retainedQuestionIds = inputs.stream().map(QuizQuestionInput::id)
                .filter(java.util.Objects::nonNull).collect(Collectors.toSet());
        questions.deleteAll(oldQuestions.values().stream().filter(q -> !retainedQuestionIds.contains(q.getId())).toList());
        questions.flush();

        List<QuizQuestion> retainedQuestions = oldQuestions.values().stream()
                .filter(q -> retainedQuestionIds.contains(q.getId())).toList();
        retainedQuestions.forEach(q -> q.moveTemporarily(q.getPosition() + 1_000_000));
        questions.saveAllAndFlush(retainedQuestions);

        for (QuizQuestionInput input : inputs) {
            QuizQuestion question;
            if (input.id() == null) {
                question = questions.saveAndFlush(new QuizQuestion(quizId, input.position(), input.prompt().strip()));
            } else {
                question = oldQuestions.get(input.id());
                question.update(input.position() + 1_000_000, input.prompt().strip());
                questions.saveAndFlush(question);
            }
            List<QuizQuestionOption> existingOptions = oldOptions.getOrDefault(question.getId(), List.of());
            Map<UUID, QuizQuestionOption> existingById = existingOptions.stream()
                    .collect(Collectors.toMap(QuizQuestionOption::getId, Function.identity()));
            Set<UUID> retainedOptionIds = input.options().stream().map(QuizOptionInput::id)
                    .filter(java.util.Objects::nonNull).collect(Collectors.toSet());
            options.deleteAll(existingOptions.stream().filter(o -> !retainedOptionIds.contains(o.getId())).toList());
            options.flush();
            List<QuizQuestionOption> retainedOptions = existingOptions.stream()
                    .filter(o -> retainedOptionIds.contains(o.getId())).toList();
            retainedOptions.forEach(o -> o.update(o.getPosition() + 1_000_000, o.getText(), false));
            options.saveAllAndFlush(retainedOptions);
            Map<QuizQuestionOption, QuizOptionInput> finalOptionValues = new java.util.LinkedHashMap<>();
            for (QuizOptionInput optionInput : input.options()) {
                if (optionInput.id() == null) {
                    QuizQuestionOption created = options.saveAndFlush(new QuizQuestionOption(question.getId(),
                            optionInput.position() + 1_000_000, optionInput.text().strip(), false));
                    finalOptionValues.put(created, optionInput);
                } else {
                    QuizQuestionOption option = existingById.get(optionInput.id());
                    finalOptionValues.put(option, optionInput);
                }
            }
            finalOptionValues.forEach((option, optionInput) -> option.update(
                    optionInput.position(), optionInput.text().strip(), optionInput.correct()));
            options.saveAllAndFlush(finalOptionValues.keySet());
            if (input.id() != null) {
                question.update(input.position(), input.prompt().strip());
                questions.save(question);
            }
        }
        questions.flush();
    }

    private void validateRetainedIds(List<QuizQuestionInput> inputs, Map<UUID, QuizQuestion> oldQuestions,
            Map<UUID, List<QuizQuestionOption>> oldOptions) {
        Set<UUID> questionIds = new HashSet<>();
        Set<UUID> optionIds = new HashSet<>();
        for (QuizQuestionInput input : inputs) {
            if (input.id() != null && (!oldQuestions.containsKey(input.id()) || !questionIds.add(input.id()))) {
                throw new ValidationException("Question ID is unknown to this Quiz or duplicated");
            }
            Set<UUID> optionsForQuestion = input.id() == null ? Set.of() : oldOptions
                    .getOrDefault(input.id(), List.of()).stream()
                    .map(QuizQuestionOption::getId).collect(Collectors.toSet());
            if (input.id() == null && input.options().stream().anyMatch(o -> o.id() != null)) {
                throw new ValidationException("An option ID cannot be retained under a new question");
            }
            for (QuizOptionInput option : input.options()) {
                if (option.id() != null && (!optionsForQuestion.contains(option.id()) || !optionIds.add(option.id()))) {
                    throw new ValidationException("Option ID is unknown to this question or duplicated");
                }
            }
        }
    }

    private void validateQuestions(List<QuizQuestionInput> inputs) {
        if (inputs == null || inputs.isEmpty()) throw new ValidationException("Quiz must contain at least one question");
        validatePositions(inputs.stream().map(QuizQuestionInput::position).toList(), "question");
        for (QuizQuestionInput question : inputs) {
            validateText(question.prompt(), "question prompt", true);
            if (question.options() == null || question.options().size() < 2) {
                throw new ValidationException("Every question must contain at least two options");
            }
            validatePositions(question.options().stream().map(QuizOptionInput::position).toList(), "option");
            long correct = question.options().stream().filter(o -> Boolean.TRUE.equals(o.correct())).count();
            if (correct != 1) throw new ValidationException("Every question must have exactly one correct option");
            for (QuizOptionInput option : question.options()) validateText(option.text(), "option text", true);
        }
    }

    private void validatePositions(List<Integer> positions, String label) {
        Set<Integer> actual = new HashSet<>(positions);
        if (actual.size() != positions.size()) throw new ValidationException("Quiz " + label + " positions must be unique");
        for (int position = 1; position <= positions.size(); position++) {
            if (!actual.contains(position)) throw new ValidationException("Quiz " + label + " positions must be contiguous from 1");
        }
    }

    private void validateText(String value, String field, boolean nonblank) {
        if (value == null || (nonblank && value.isBlank())) throw new ValidationException(field + " is required");
    }

    private Quiz load(UUID quizId) { return quizzes.findById(quizId).orElseThrow(this::notFound); }
    private ResourceNotFoundException notFound() { return new ResourceNotFoundException("Quiz not found"); }

    private record ResolvedAnswer(QuizQuestion question, List<QuizQuestionOption> options,
            QuizQuestionOption selected, QuizQuestionOption correct, boolean isCorrect) { }
}
